# Generated by Django 5.0.7 on 2024-07-14 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='nutritionist_id',
            new_name='nutritionist',
        ),
    ]
