# Generated by Django 5.0.7 on 2024-07-16 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_rename_nutritionist_id_patient_nutritionist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fat_percentual', models.DecimalField(decimal_places=1, max_digits=4)),
                ('muscle_percentual', models.DecimalField(decimal_places=1, max_digits=4)),
                ('hdl_colesterol', models.IntegerField()),
                ('ldl_colesterol', models.IntegerField()),
                ('total_colesterol', models.IntegerField()),
                ('triglycerides', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.patient')),
            ],
        ),
    ]
